export const Rome = [
    { name: "Republican Legionaries", cost: 3 },
    { name: "Italian Infatry", cost: 2 },
    { name: "Imperial Legionaries *", cost: 3 },
    { name: "Imperial Auxilliaries *", cost: 2 },
    { name: "Imperial Praetoran *", cost: 4 },
    { name: "Velites", cost: 2 },
    { name: "Auxiliary Archers *", cost: 2 },
    { name: "Allied Cavalry", cost: 3 },
    { name: "Imperial Legionary Cavalry *", cost: 2 },
    { name: "Imperial Praetoran Cavalry *", cost: 3 },
    { name: "Scoprio *", cost: 1 },
    { name: "Ballistate *", cost: 2 },
    { name: "Onager *", cost: 3 },
    { name: "Ship Cards", cost: 2 },
    { name: "Road", cost: 1 },
    { name: "Police Unrest", cost: 1 },
    { name: "New 2 Star General", cost: 2 },
    { name: "Replacement Agent", cost: 2 },
    { name: "Defensive Walling", cost: 2 },
    { name: "Market", cost: 2 },
    { name: "Barracks", cost: 2 },
    { name: "Developmet (worth 1)", cost: 1 },
    { name: "Developmet (worth 2)", cost: 2 },
    { name: "Developmet (worth 3)", cost: 3 },
    { name: "Developmet (worth 4)", cost: 4 },
    { name: "Developmet (worth 5)", cost: 5 },
    
  ];

  export const Carthage = [
    { name: "Libyan Spearmen", cost: 2 },
    { name: "Citizen Spearmen", cost: 3 },
    { name: "Sacred Band *", cost: 4 },
    { name: "Hispanic Scutarii", cost: 3 },
    { name: "Numidian Javelinmen", cost: 1 },
    { name: "Balearic Slingers", cost: 1 },
    { name: "Numidian Cavalry", cost: 1 },
    { name: "Citizen Cavalry", cost: 3 },
    { name: "Poeni Cavalry", cost: 4 },
    { name: "Hispanic Cavalry", cost: 3 },
    { name: "War Elephants *", cost: 4 },
    { name: "Ballistate *", cost: 2 },
    { name: "Onager *", cost: 3 },
    { name: "Ship Cards", cost: 2 },
    { name: "Road", cost: 1 },
    { name: "Police Unrest", cost: 1 },
    { name: "New 2 Star General", cost: 2 },
    { name: "Replacement Agent", cost: 2 },
    { name: "Defensive Walling", cost: 2 },
    { name: "Market", cost: 2 },
    { name: "Barracks", cost: 2 },
    { name: "Developmet (worth 1)", cost: 1 },
    { name: "Developmet (worth 2)", cost: 2 },
    { name: "Developmet (worth 3)", cost: 3 },
    { name: "Developmet (worth 4)", cost: 4 },
  ];

  export const Barbarians = [
    { name: "Lowland Warriors", cost: 2 },
    { name: "Highland  Warriors", cost: 2 },
    { name: "Soldurii", cost: 4 },
    { name: "Naked Geasatae *", cost: 3 },
    { name: "Javelinmen", cost: 1 },
    { name: "Slingers", cost: 1 },
    { name: "Pony Riders *", cost: 1 },
    { name: "Heavy Cavalry *", cost: 2 },
    { name: "Noble Cavalry *", cost: 3 },
    { name: "Chariots", cost: 2 },
    { name: "Ship Cards *", cost: 2 },
    { name: "Road", cost: 1 },
    { name: "Police Unrest", cost: 1 },
    { name: "New 2 Star General (free)", cost: 0 },
    { name: "Replacement Agent", cost: 2 },
    { name: "Defensive Walling", cost: 2 },
    { name: "Market", cost: 2 },
    { name: "Barracks", cost: 2 },
    { name: "Developmet (worth 1)", cost: 1 },
    { name: "Developmet (worth 2)", cost: 2 },
    { name: "Developmet (worth 3)", cost: 3 },
    { name: "Developmet (worth 4)", cost: 4 },
  ];

  export const Greece = [
    { name: "Hopilites", cost: 2 },
    { name: "Phalangites *", cost: 3 },
    { name: "Illyrian Infantry", cost: 2 },
    { name: "Peltastoi", cost: 2 },
    { name: "Argrianian Javelinmen", cost: 1 },
    { name: "Cretan Archers", cost: 2 },
    { name: "Javelinmen", cost: 1 },
    { name: "Rhodian Slingers", cost: 1 },
    { name: "Thracian Cavalry", cost: 1 },
    { name: "Thessalian Cavalry", cost: 3 },
    { name: "Companians", cost: 4 },
    { name: "War Elephants *", cost: 4 },
    { name: "Ballistate *", cost: 2 },
    { name: "Onager *", cost: 3 },
    { name: "Ship Cards", cost: 2 },
    { name: "Road", cost: 1 },
    { name: "Police Unrest", cost: 1 },
    { name: "New 2 Star General", cost: 2 },
    { name: "Replacement Agent", cost: 2 },
    { name: "Defensive Walling", cost: 2 },
    { name: "Market", cost: 2 },
    { name: "Barracks", cost: 2 },
    { name: "Developmet (worth 1)", cost: 1 },
    { name: "Developmet (worth 2)", cost: 2 },
    { name: "Developmet (worth 3)", cost: 3 },
    { name: "Developmet (worth 4)", cost: 4 },
  ];